site_name: DeepGoTrackIt
site_url: https://mydomain.org/deepgotrackit

theme:
  name: material
  font:
    text: Roboto

#  logo: assets/gotrackit-logo.png
  icon:
    annotation: material/arrow-right-circle

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.prune
#    - toc.integrate

  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - HomePage: index.md
  - GettingStarted: license.md
  - UserGuide:
      - 如何下载: UserGuide/如何下载.md
      - 数据要求: UserGuide/数据要求.md
      - 路网生产与优化: UserGuide/路网生产与优化.md
      - 轨迹生产: UserGuide/轨迹生产.md
      - 轨迹处理: UserGuide/轨迹处理.md
      - 路径匹配: UserGuide/路径匹配.md
  - ExampleGallery:
      - 轨迹匹配后生成仿真: ExampleGallery/轨迹匹配后生成仿真.md
  - SourceCode:
      - SourceCode: SourceCode/SpreadPortfolio.md
  - 样式参考:
      - 样式: format.md


plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - def_list
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  version:
    provider: mike